name: yu_ni_player_workspace
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

workspace:
  - packages/yu_ni_player
  - packages/yu_ni_player_video_player_kit
  - packages/yu_ni_player_tx_player
  - packages/yu_ni_player_media_kit
  - example
