name: yu_ni_player_example
description: Example app demonstrating yu_ni_player multi-package usage.
version: 1.0.0

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  yu_ni_player_base:
    git:
      url: https://git.uneed.com/unix/flugins/yu_ni_player.git
      ref: 1.0.3
      path: ./yu_ni_player_base
  yu_ni_player_video_player_kit:
    git:
      url: https://git.uneed.com/unix/flugins/yu_ni_player.git
      ref: 1.0.3
      path: ./yu_ni_player_video_player_kit
  yu_ni_player_tx_player:
    git:
      url: https://git.uneed.com/unix/flugins/yu_ni_player.git
      ref: 1.0.3
      path: ./yu_ni_player_tx_player
  yu_ni_player_media_kit:
    git:
      url: https://git.uneed.com/unix/flugins/yu_ni_player.git
      ref: 1.0.3
      path: ./yu_ni_player_media_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
