name: yu_ni_player_media_kit
description: media_kit engine implementation for yu_ni_player, providing high-performance video playback on Linux.
version: 1.0.3
homepage: https://github.com/lurongshuang/yu_ni_player/tree/main/yu_ni_player_media_kit
repository: https://github.com/lurongshuang/yu_ni_player
issue_tracker: https://github.com/lurongshuang/yu_ni_player/issues

topics:
  - video
  - player
  - linux
  - media-kit

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  yu_ni_player_base:
    git:
      url: https://git.uneed.com/unix/flugins/yu_ni_player.git
      ref: 1.0.3
      path: ./yu_ni_player_base
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
