name: yu_ni_player_base
description: Abstract base library for yu_ni_player multi-engine Flutter video player plugin with zero-dependency on specific SDKs.
version: 1.0.1
homepage: https://github.com/lurongshuang/yu_ni_player/tree/main/yu_ni_player_base
repository: https://github.com/lurongshuang/yu_ni_player
issue_tracker: https://github.com/lurongshuang/yu_ni_player/issues

topics:
  - video
  - player
  - engine
  - abstraction

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  glados: ^1.1.7

flutter:
  uses-material-design: true
